#!/usr/bin/env python3
# Licence GPLv3

import requests
import json
import logging
import itertools
from os import path

logging.basicConfig(format='%(asctime)-15s %(message)s', level=logging.INFO)

# config_dir = "conf"
config_dir = "/etc/py-hole"
# blackhole_file = "blackhole.list"
blackhole_file = "/var/lib/py-hole/blackhole.list"

source_file = path.join(config_dir, "adlists.default")
config_file = path.join(config_dir, "py-hole.json")
always_file = path.join(config_dir, "always")
never_file = path.join(config_dir, "never")


def uncomment(line):
    return line.partition('#')[0].rstrip()


def non_empty_after_uncommented(i):
    uncommented = (uncomment(line) for line in i)
    return [line for line in uncommented if len(line.strip()) != 0]


def read_sources(filepath):
    with open(filepath) as f:
        return non_empty_after_uncommented(f)


def load_source(url):
    response = requests.get(url, timeout=60)
    response.raise_for_status()
    return response.text.split('\n')


def hosts_from(hosts_file_or_host_list):
    def host_from(l):
        r = l.split()
        if len(r) == 1:
            return r[0]
        else:
            return r[1]

    return set(host_from(l) for l in non_empty_after_uncommented(hosts_file_or_host_list))


hosts = set()

with open("%s/py-hole.json" % config_dir) as c:
    config = json.load(c)

for source in read_sources(source_file):
    logging.info("Getting '%s'", source)
    hosts.update(hosts_from(load_source(source)))

logging.info("Have %d hosts to blackhole from sources", len(hosts))

with(open(always_file)) as always:
    always_hosts = hosts_from(always.readlines())

logging.info("Adding %d hosts that must always be blackholed", len(always_hosts))
hosts.update(always_hosts)

with(open(never_file)) as never:
    never_hosts = hosts_from(never.readlines())

logging.info("Removing %d hosts that must never be blackholed", len(never_hosts))
hosts.difference_update(never_hosts)

logging.info("Have %d hosts to blackhole from sources", len(hosts))

sorted_hosts = list(hosts)
sorted_hosts.sort()

with(open(blackhole_file, "w")) as blackhole:
    for host in itertools.chain({"py-hole.blackhole.host"}, sorted_hosts):
        blackhole.write("%s\t%s\n" % (config["ip"]["v4"], host))

logging.info("Complete")
